### ISSUE TITLE
Logger return an error  

### ISSUE THREAD

**Issue by PatrickImbo** [robintw/PyFMask#3]
Dear Robin,

The logger line:
       logger.info("Final Cloud Layer Percent: %f" %
                ((float(Cloud[cloud_mask].sum()) / float(mask.sum())) \* 100.0))
return a divide by zero error.

To bypass the error I catch the exception. Is it 'the' correct way ?

Best regards,
Patrick

INFO:root.PyFMask.fmask:From DNs to TOA ref & BT
/usr/local/lib/python2.7/dist-packages/PyFMask-3.2.0-py2.7.egg/PyFMask/fmask.py:900: RuntimeWarning: divide by zero encountered in long_scalars
/usr/local/lib/python2.7/dist-packages/PyFMask-3.2.0-py2.7.egg/PyFMask/fmask.py:903: RuntimeWarning: divide by zero encountered in long_scalars
Traceback (most recent call last):
  File "/usr/local/bin/fmask.py", line 9, in <module>
    load_entry_point('PyFMask==3.2.0', 'console_scripts', 'fmask.py')()
  File "build/bdist.linux-x86_64/egg/PyFMask/fmask.py", line 2021, in main

  File "build/bdist.linux-x86_64/egg/PyFMask/fmask.py", line 1955, in run_FMask

  File "build/bdist.linux-x86_64/egg/PyFMask/fmask.py", line 1128, in plcloud

ZeroDivisionError: float division by zero

**Comment by PatrickImbo** [comment]
Hi,
Processing L8 data with TIRS anomalies cause this fatal error.
Regards,
Patrick

**Comment by robintw** [comment]
Yes, you should be able to either just catch the exception with a try-catch block, or potentially just comment out the code.

However, please be aware of the notice at the top of the README file on the front page of this project: "There are major issues in the code, and it should not be used in its current state. I suggest you investigate https://bitbucket.org/chchrsc/python-fmask instead" - so I would strongly suggest not using this code (and I will not be able to provide any further support).
